export class UserManagementPage {
    static firstSection = () => cy.get('section').eq(0)
    static secondSection = () => cy.get('section').eq(1)
    static thirdSection = () => cy.get('section').eq(3)
    static adminEmailInput = () => cy.get('#admin-email')
    static adminPasswordInput = () => cy.get('#admin-password')
    static adminSubmitButton = () => cy.get("[class*='btn-primary']").first()
    static successSignInMessage = () => cy.contains('#admin-controls', 'You are logged in as admin.')
    static logoutButton = () => cy.get("[class*='btn-secondary']").first().should('contain.text', 'Logout')
    static popUpConfirmDeleteButton = () => cy.get('#confirm-delete')
    static userTableRows = () => cy.get('tbody tr')
    static invalidCredentials = () => cy.contains('#login-status', 'Invalid credentials')
    static userTable = () => cy.get('#user-table')
    static userTableBody = () => cy.get('#user-table tbody')
    static editButtonInTable = () => cy.get('.btn-secondary.edit-btn')
    static firstEditButtonInTable = () => cy.get('.btn-secondary.edit-btn').eq(0)
    static secondEditButtonInTable = () => cy.get('.btn-secondary.edit-btn').eq(1)
    static thirdEditButtonInTable = () => cy.get('.btn-secondary.edit-btn').eq(2)
    static fourthEditButtonInTable = () => cy.get('.btn-secondary.edit-btn').eq(3)
    static firstRowInUserTable = () => cy.get('tbody tr').eq(0)
    static secondRowInUserTable = () => cy.get('tbody tr').eq(1)
    static thirdRowInUserTable = () => cy.get('tbody tr').eq(2)
    static fourthRowInUserTable = () => cy.get('tbody tr').eq(3)
    static deleteButtonInTable = () => cy.get('.btn-danger.delete-btn')
    static userTableFirstDeleteButton = () => cy.get('.btn-danger.delete-btn').eq(0)
    static userTableSecondDeleteButton = () => cy.get('.btn-danger.delete-btn').eq(1)
    static userTableThirdDeleteButton = () => cy.get('.btn-danger.delete-btn').eq(2)
    static userTableFourthDeleteButton = () => cy.get('.btn-danger.delete-btn').eq(3)
    static userTableStatusChangeButton = () => cy.get('td button.btn-primary')
    static userTableFirstStatusChangeButton = () => cy.get('td button.btn-primary').eq(0)
    static userTableSecondStatusChangeButton = () => cy.get('td button.btn-primary').eq(1)
    static userTableThirdStatusChangeButton = () => cy.get('td button.btn-primary').eq(2)
    static userTableFourthStatusChangeButton = () => cy.get('td button.btn-primary').eq(3)               
    static nameField = () => cy.get('#name')
    static roleField = () => cy.get('#role')
    static roleOptionAdmin = () => cy.get('option[value="Admin"]')
    static roleOptionEditor = () => cy.get('option[value="Editor"]')
    static roleOptionViewer = () => cy.get('option[value="Viewer"]')
    static ageField = () => cy.get('#age')
    static emailField = () => cy.get('#email')
    static genderMaleRadioButton = () => cy.get('input[value="Male"]')
    static genderFemaleRadioButton = () => cy.get('input[value="Female"]')
    static genderOtherRadioButton = () => cy.get('input[value="Other"]')
    static newsletterCheckbox = () => cy.get('input[value="Newsletter"]')
    static productUpdatesCheckbox = () => cy.get('input[value="Product Updates"]')
    static addNewUserSaveButton = () => cy.get('#user-form button[type="submit"]')
    static nameDataUserTable = () => cy.get('td').eq(0)
    static roleDataUserTable = () => cy.get('td').eq(1)
    static ageDataUserTable = () => cy.get('td').eq(2)
    static emailDataUserTable = () => cy.get('td').eq(3)
    static genderDataUserTable = () => cy.get('td').eq(4)
    static subscriptionDataUserTable = () => cy.get('td').eq(5)
    static statusDataUserTable = () => cy.get('td').eq(6)
    static adminDeleteError = () => cy.get('div#admin-delete-error')
    static nameFieldError = () => cy.contains('ul li', 'Name must be 1–20 letters only (no spaces or symbols).')
    static roleFieldError = () => cy.contains('ul li', 'Role is required.')
    static ageFieldError = () => cy.contains('ul li', 'Age must be between 1 and 99.')
    static emailFieldError = () => cy.contains('ul li', 'Valid email is required.')
    static genderFieldError = () => cy.contains('ul li', 'Gender selection is required.')
}