name: Build and Check
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  TSC-Check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: # Set NODE_OPTIONS for the entire job
      NODE_OPTIONS: "--max_old_space_size=4096"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: npm install
        run: npm install
      - name: Run TSC check for all files in the repo
        run: npm run tsc
  ESLint-Check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: # Set NODE_OPTIONS for the entire job
      NODE_OPTIONS: "--max_old_space_size=4096"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: npm install
        run: npm install
      - name: Run ESLint for all files in the repo
        run: npm run eslint -- --ext .ts ./
  Prettier-Check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: npm install
        run: npm install
      - name: Run Prettier for the files that were changed in the PR
        run: npm run prettier -- --check $(git diff origin/${{ github.event.pull_request.base.ref }}..HEAD --name-only --diff-filter d | grep '.ts$' | xargs)
